export const environment = {
    apiURL: 'https://fed-api.sewnstaging.com',
    wsEndpoint: 'wss://messaging.sewnstaging.com/v1',
    encryptionKey: 'sewen_secrete_key',
    ssoWeb: 'https://sso.sewnstaging.com',
    estatesWeb: 'https://estates.sewnstaging.com',
    facilitatorWeb: 'https://operator.sewnstaging.com',
    roasterWeb: 'https://roaster.sewnstaging.com',
    microRoasterWeb: 'https://microroaster.sewnstaging.com',
    horecaWeb: 'https://partners.sewnstaging.com',
    adminWeb: 'https://admin.sewnstaging.com',
    agroUrl: 'https://api.agromonitoring.com/agro/1.0/',
    estateBrandProfileUrl: 'https://www.sewnstaging.com/estate',
    roasterBrandProfileUrl: 'https://www.sewnstaging.com/roaster',
    coffeeLabWeb: 'https://www.sewnstaging.com/coffee-lab/',
    supportEmailAddress: 'support@eraofwe.com',
    termsUserUrl: 'https://support.eraofwe.com/en/kb/articles/general-terms-conditions-user',
    termsEntityUrl: 'https://support.eraofwe.com/en/kb/articles/general-terms-conditions-legal-entity',
    privacyPolicyUrl: 'https://support.eraofwe.com/en/kb/articles/privacy-policy',
    cookiePolicyUrl: 'https://support.eraofwe.com/en/kb/articles/cookie-policy',
    protectNeed: true,
    production: true,
};
