export const environment = {
    apiURL: 'https://fed-api.sewnstaging.com',
    wsEndpoint: 'wss://messaging.sewnstaging.com/v1',
    encryptionKey: 'sewen_secrete_key',
    ssoWeb: 'https://sso.sewnstaging.com',
    estatesWeb: 'https://estates.sewnstaging.com',
    facilitatorWeb: 'https://operator.sewnstaging.com',
    roasterWeb: 'https://roaster.sewnstaging.com',
    microRoasterWeb: 'https://microroaster.sewnstaging.com',
    horecaWeb: 'https://partners.sewnstaging.com',
    adminWeb: 'https://admin.sewnstaging.com',
    agroUrl: 'https://api.agromonitoring.com/agro/1.0/',
    estateBrandProfileUrl: 'https://www.sewnstaging.com/estate',
    roasterBrandProfileUrl: 'https://www.sewnstaging.com/roaster',
    production: true,
};
