export const APP_LANGUAGES: any[] = [
    {
        label: {
            en: 'English',
            sv: 'Engelska',
            pt: 'Inglês',
            es: 'Inglés',
            da: 'Engelsk',
            fr: 'Anglais',
            de: 'Englisch',
            nl: 'Engels',
            it: 'Inglese',
        },
        value: 'en',
        countries: [],
    },
    {
        label: {
            en: 'Swedish',
            sv: 'Svenska',
            pt: 'Sueca',
            es: 'Sueca',
            da: 'Svensk',
            fr: 'Suédois',
            de: 'Schwedisch',
            nl: 'Zweeds',
            it: 'Svedese',
        },
        value: 'sv',
        countries: ['SV'],
    },
    {
        label: {
            en: 'Portuguese',
            sv: 'Portugisiska',
            pt: 'Português',
            es: 'Portuguesa',
            da: 'Portugisisk',
            fr: 'Portugais',
            de: 'Portugiesisch',
            nl: 'Portugees',
            it: 'Portoghese',
        },
        value: 'pt',
        countries: ['PT', 'BR', 'IN'],
    },
    {
        label: {
            en: 'Spanish',
            sv: 'Spanska',
            pt: 'Espanhola',
            es: 'Español',
            da: 'Spansk',
            fr: 'Espagnol',
            de: 'Spanisch',
            nl: 'Spaans',
            it: 'Spagnolo',
        },
        value: 'es',
        countries: ['ES'],
    },
    {
        label: {
            en: 'Danish',
            sv: 'Danska',
            pt: 'Dinamarquês',
            es: 'Danés',
            da: 'Dansk',
            fr: 'Danois',
            de: 'Dänisch',
            nl: 'Deens',
            it: 'Danese',
        },
        value: 'da',
        countries: ['DA'],
    },
    {
        label: {
            en: 'French',
            sv: 'franska',
            pt: 'Francês',
            es: 'Francés',
            da: 'Fransk',
            fr: 'Français',
            de: 'Französisch',
            nl: 'Frans',
            it: 'Francese',
        },
        value: 'fr',
        countries: ['FR'],
    },
    {
        label: {
            en: 'German',
            sv: 'Tysk',
            pt: 'Alemão',
            es: 'Alemán',
            da: 'Tysk',
            fr: 'Allemand',
            de: 'Deutsch',
            nl: 'Duitse',
            it: 'Tedesco',
        },
        value: 'de',
        countries: ['DE'],
    },
    {
        label: {
            en: 'Dutch',
            sv: 'Holländska',
            pt: 'Holandês',
            es: 'Holandés',
            da: 'Hollandske',
            fr: 'Néerlandais',
            de: 'Niederländisch',
            nl: 'Nederlands',
            it: 'Olandese',
        },
        value: 'nl',
        countries: ['NL'],
    },
    {
        label: {
            en: 'Italian',
            sv: 'Italienska',
            pt: 'Italiano',
            es: 'Italiano',
            da: 'Italiensk',
            fr: 'Italien',
            de: 'Italienisch',
            nl: 'Italiaans',
            it: 'Italiano',
        },
        value: 'it',
        countries: ['IT'],
    },
];

export const LANGUAGE_PREFIXES: string[] = ['en', 'sv', 'pt-br', 'es'];
